FROM python:3.9-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
# apk -> alpine linux's package management system
RUN apk update \
    && apk add gcc python3-dev musl-dev postgresql-dev

# install dependencies
RUN pip3 install --upgrade pip
RUN python3 -m pip install pipenv
COPY ./Pipfile .
COPY ./Pipfile.lock .
RUN pipenv install --system --deploy --ignore-pipfile
RUN pipenv sync


# copy project
COPY . .
