version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  postgres_data:
